# Maths - Form & Function: Chapter 5 (Functions, Transformations, and Groups)

## 1. Types of Functions

Composite functions can be formed by substituting the elements of 1 function into a final form, as the quadratic equation (alt version) below is created from the micro functions in the 1st form.

In [11]:
# Proving equivalence of 2 formas of the quadratic equation:

def quadratic_equation(x):
    """ An example of the quadratic equation. """
    y = 2 + x
    z = 3 * y
    return z**2

def alt_quadratic_equation(x):
    """ An alternative form of the quadratic equation. """
    return 36 + 36 * x + 9 * x**2

print(quadratic_equation(1))
print(alt_quadratic_equation(1))
print(quadratic_equation(2))
print(alt_quadratic_equation(2))

81
81
144
144


Some functions are not defined for all real numbers, for example, the below is not defined for x = 1 or x = 2:

In [150]:
import math

# The following function excludes x == 1 or x == 2:
def rational_function(x):
    """ An example of the rational function. """
    try:
        numerator = (3 * math.pow(x, 2)) - 1
        denominator = math.pow(x, 2) - (3 * x) + 2
        #print("d" + str(denominator))
        return numerator / denominator
    except ZeroDivisionError:
        return "Division by Zero!"

print(rational_function(1))
print(rational_function(-1))
print(rational_function(2))
print(rational_function(-2))

Division by Zero!
0.3333333333333333
Division by Zero!
0.9166666666666666


In [155]:
# Another function over only a subset of Real numbers:
def square_root_function(x):
    """ Demonstrates square root only for positives. """
    try:
        return math.sqrt(x)
    except ValueError:
        return "No square root for negative numbers!"
    
print(square_root_function(1))
print(square_root_function(0))
print(square_root_function(-1))

1.0
0.0
No square root for negative numbers!


Functions may be determined by several different operations, as in the below:

In [157]:
def multiple_operation_demonstration(x):
    """ Simple demonstration of function with multiple operations. """
    if x >= 0:
        return x
    else:
        return -x
    
print(multiple_operation_demonstration(1))
print(multiple_operation_demonstration(0))
print(multiple_operation_demonstration(-1))

1
0
1


Following are some examples of physical formulas based on elementary laws:

In [171]:
def weight(density, volume):
    """ Calculate weight from density & volume. """
    return density * volume

print(weight(.5, 10))

def distance(time, gravity = 9.807):
    """ Calculates distance fallen in time. """
    return (gravity * time ** 2) / 2

print(distance(5))

5.0
122.5875


## 2. Maps

> ... "maps" - that is, functions, from one set *X* of objects, points, or numbers into some other set *Y*.

In [28]:
def transformation(x, y):
    """ Demonstration of transformationn of 2 vectors. """
    a, c = x
    b, d = y
    x, y = tuple(map(sum, [(1, 0), (0, 1)]))
    return (a * x + b * y, c * x + d * y)

a, b, c, d = 0, 1, 2, 3
print(transformation((a, c), (b, d)))

(1, 5)


In [29]:
import numpy as np

matrix_a = np.array([[a, b], [c, d]])
matrix_b = np.array([[a, d], [b, c]])

print(matrix_a)
print(matrix_b)
print(matrix_a @ matrix_b)

[[0 1]
 [2 3]]
[[0 3]
 [1 2]]
[[ 1  2]
 [ 3 12]]


## 3. What is a Function?

Intuitive (but imperfect) definitions of functions include:

- *Formula* - with x as a value, the formula produces a number
- *Rule* - rules applied to x produces corresponding value y
- *Graph* - b is a point on a curve in geometric space matching a
- *Dependence* - a determination of x fixes y, so y depends on x
- *Table of Values* - each x in a table has a corresponding y value
- *Syntax* - *f x* is just a symbolic representation of y

Each of these definitions has problems.

## 4. Functions as Sets of Pairs